path:  /Users/hirahara/Documents/Python Scripts/sentan2023/20230713_yolov8_train/dataset/nakaizu_stem_night_s-20_k2b
train: train/images
val:   valid/images
test:  test/images

nc: 2

names:
  0:
  1: grape_cane_kp
